# Generated by Django 5.2.3 on 2025-06-27 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField()),
                ('monto_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minicoreapp.vendedor')),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minicoreapp.regla')),
            ],
        ),
    ]
